const SHARED=[
['seed_1','advisability','целесообразность'],['seed_2','participate','участвовать'],['seed_3','spacecraft / space vehicle','космический аппарат'],['seed_4','requirements','требования'],['seed_5','necessities','предметы первой необходимости'],['seed_6','guaranteed','гарантированный'],['seed_7','bulky','громоздкий'],['seed_8','entrusted','порученный, доверенный'],['seed_9','unmanned','беспилотный'],['seed_10','probes','зонды'],['seed_11','malfunction','неисправность'],['seed_12','weightlessness','невесомость'],['seed_13','encounter','сталкиваться с'],['seed_14','precious','ценный'],['seed_15','lacking','отсутствующий'],['seed_16','specifically','специально'],['seed_17','deep space','дальний космос'],['seed_18','reasoning','рассуждение, логическое мышление'],['seed_19','fulfilled','выполненный, осуществлённый'],['seed_20','simulate','имитировать'],['seed_21','substitution','замена'],['seed_22','revise','пересматривать'],['seed_23','collaborative','совместный'],['seed_24','apparent','очевидный, заметный'],['seed_25','compromise','подвергать риску, ставить под угрозу'],['seed_26','evolve','развиваться'],['seed_27','outpost','аванпост, удалённая база'],['seed_28','infrastructure','инфраструктура'],['seed_29','vicinity','окрестность, близость'],['seed_30','enterprises','предприятия'],['seed_31','essential','необходимый'],['seed_32','voyage','путешествовать'],['seed_33','frontier','граница, новый рубеж'],['seed_34','colonisation','колонизация, заселение'],['seed_35','consciousness','осознание, сознание'],['seed_36','fragility','хрупкость'],['seed_37','preserve','сохранять']
].map(x=>({id:x[0],word:x[1],translation:x[2],category:'Space English',example:'',shared:true,level:0,correct:0,wrong:0,seen:0,nextReview:0}));
const KEY='slovotrener_live_v1';
const MODE_NAMES={smart:'🧠 Умная смесь',flash:'🃏 Карточки',toTr:'🇬🇧→🇷🇺 Перевод',toWord:'🇷🇺→🇬🇧 Перевод',choice:'✅ Тест',listen:'🎧 Аудирование',mistakes:'🔥 Ошибки'};
const empty=()=>({words:[],stats:{sessions:0,correct:0,total:0,streak:0,lastDate:null,daily:{}}});
function norm(s){return String(s||'').trim().toLowerCase().replace(/[.,!?;:"'`]/g,'').replace(/\s+/g,' ')}
function load(){let st;try{st=JSON.parse(localStorage.getItem(KEY))||empty()}catch{st=empty()}st.words ||= [];st.stats ||= empty().stats;st.stats.daily ||= {};for(const sw of SHARED){let w=st.words.find(x=>x.id===sw.id||norm(x.word)===norm(sw.word));if(w){w.id=sw.id;w.word=sw.word;w.translation=sw.translation;w.category=sw.category;w.shared=true}else st.words.push(structuredClone(sw))}return st}
let state=load(),sess=null,selectedMode='smart';
const $=id=>document.getElementById(id);
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]))}
function todayKey(){return new Date().toISOString().slice(0,10)}
function due(w){return !w.nextReview||w.nextReview<=Date.now()}
function go(id){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('on',x.id===id));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('on',x.dataset.v===id));scrollTo(0,0)}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>go(b.dataset.v));
function render(){ $('sWords').textContent=state.words.length;$('sDue').textContent=state.words.filter(due).length;$('sAcc').textContent=(state.stats.total?Math.round(state.stats.correct/state.stats.total*100):0)+'%';$('sSessions').textContent=state.stats.sessions;$('streak').textContent=state.stats.streak||0;let d=state.stats.daily[todayKey()];$('todaySummary').textContent=d?`${d.sessions} тренировок · ${d.total} заданий · ${Math.round(d.correct/Math.max(1,d.total)*100)}% верно`:'Пока тренировок не было.';renderList();renderCats();renderWeak();$('warn').innerHTML=state.words.length<4?'<div class="notice">Добавь минимум 4 слова для разнообразной тренировки.</div>':'';}
function renderList(){let q=norm($('search').value),arr=state.words.filter(w=>!q||norm(w.word+' '+w.translation+' '+w.category).includes(q));$('list').innerHTML=arr.length?arr.map(w=>`<div class="wordrow"><div class="word">${esc(w.word)}</div><div class="translation">${esc(w.translation)}</div><div class="meta">${esc(w.category||'Без категории')} · ✓ ${w.correct||0} · ✕ ${w.wrong||0}${w.shared?' · общий':''}</div>${w.shared?'':`<button class="danger" data-del="${w.id}">Удалить</button>`}</div>`).join(''):'<div class="sub">Ничего не найдено.</div>';$('list').querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state.words=state.words.filter(w=>w.id!==b.dataset.del);save()})}
$('search').oninput=renderList;
function renderCats(){let cur=$('category').value,c=[...new Set(state.words.map(w=>w.category).filter(Boolean))].sort();$('category').innerHTML='<option value="">Все категории</option>'+c.map(x=>`<option>${esc(x)}</option>`).join('');if(c.includes(cur))$('category').value=cur}
function renderWeak(){let arr=[...state.words].filter(w=>(w.wrong||0)>0).sort((a,b)=>(b.wrong||0)-(a.wrong||0)||(a.correct||0)-(b.correct||0)).slice(0,5);$('weakList').innerHTML=arr.length?arr.map(w=>`<div class="weak"><div><strong>${esc(w.word)}</strong><br><span>${esc(w.translation)}</span></div><span>✕ ${w.wrong||0}</span></div>`).join(''):'Ошибок пока нет.'}
$('addBtn').onclick=()=>{let word=$('newWord').value.trim(),translation=$('newTr').value.trim();if(!word||!translation)return alert('Заполни слово и перевод');if(state.words.some(w=>norm(w.word)===norm(word)))return alert('Такое слово уже есть');state.words.unshift({id:'user_'+Date.now(),word,translation,category:$('newCat').value.trim()||'Мои слова',example:$('newEx').value.trim(),shared:false,level:0,correct:0,wrong:0,seen:0,nextReview:0});$('newWord').value=$('newTr').value=$('newEx').value='';save()};
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function weighted(words){let bag=[];words.forEach(w=>{let accuracy=(w.correct||0)+(w.wrong||0)?(w.correct||0)/((w.correct||0)+(w.wrong||0)):0;let weight=1+(w.wrong||0)*2+(due(w)?2:0)+(accuracy<.6?2:0);weight=Math.min(10,weight);for(let i=0;i<weight;i++)bag.push(w)});return bag.length?bag:words}
function selectMode(m){selectedMode=m;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('on',x.dataset.mode===m))}
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>selectMode(b.dataset.mode));
function eligibleWords(){let pool=state.words.filter(w=>!$('category').value||w.category===$('category').value);if(selectedMode==='mistakes'){let mistakes=pool.filter(w=>(w.wrong||0)>0);if(mistakes.length)pool=mistakes}return pool}
function smartExercise(){let r=Math.random();if(r<.22)return'flash';if(r<.45)return'toTr';if(r<.66)return'toWord';if(r<.84)return'choice';return'listen'}
function start(n,forcedMode=null){if(forcedMode)selectMode(forcedMode);let pool=eligibleWords();if(!pool.length)return alert('Нет слов для этой тренировки');let total=n==='all'?pool.length:Number(n),bag=(selectedMode==='smart'||selectedMode==='mistakes')?weighted(pool):pool,qs=[],recent=[];for(let i=0;i<total;i++){let cand=bag.filter(w=>!recent.includes(w.id));if(!cand.length)cand=bag;let w=cand[Math.floor(Math.random()*cand.length)];recent.push(w.id);if(recent.length>Math.min(3,pool.length-1))recent.shift();let m=selectedMode==='smart'||selectedMode==='mistakes'?smartExercise():selectedMode;qs.push({id:w.id,m})}sess={qs,i:0,correct:0,total:0,mode:selectedMode};$('setup').classList.add('hide');$('result').classList.add('hide');$('session').classList.remove('hide');showQ()}
$('startBtn').onclick=()=>start($('count').value);$('smartQuick').onclick=()=>{go('train');start('10','smart')};$('flashQuick').onclick=()=>{go('train');start('10','flash')};
function cw(){return state.words.find(w=>w.id===sess.qs[sess.i].id)}
function showQ(){if(sess.i>=sess.qs.length)return finish();let q=sess.qs[sess.i],w=cw();if(!w){sess.i++;return showQ()}$('counter').textContent=`${sess.i+1} / ${sess.qs.length}`;$('live').textContent=`верно ${sess.correct}`;$('bar').style.width=(sess.i/sess.qs.length*100)+'%';$('modeBadge').textContent=MODE_NAMES[sess.mode]||'Тренировка';$('qhint').textContent=w.category||'';$('answer').innerHTML='';$('questionBody').innerHTML='';if(q.m==='toTr')typedQ('Переведи слово',w.word,w.translation,false);else if(q.m==='toWord')typedQ('Напиши по-английски',w.translation,w.word,false);else if(q.m==='choice')choiceQ(w);else if(q.m==='listen')listenQ(w);else flashQ(w)}
function typedQ(type,prompt,correct){$('qtype').textContent=type;$('questionBody').innerHTML=`<div class="qword">${esc(prompt)}</div>`;$('answer').innerHTML='<input id="typedInput" placeholder="Введи ответ…" autocomplete="off" autocapitalize="none"><div class="actions" style="justify-content:center"><button class="btn" id="checkTyped">Проверить</button></div>';let input=$('typedInput');input.focus();let check=()=>{let val=input.value.trim();if(!val)return;let ok=answerOK(val,correct);record(ok);$('answer').innerHTML=`<div class="resultBox ${ok?'good':'bad'}"><b>${ok?'Верно ✓':'Неверно ✕'}</b>${ok?'':`<div style="margin-top:6px;color:var(--text)">Правильно: <b>${esc(correct)}</b></div>`}</div><div class="actions" style="justify-content:center"><button class="btn" id="nextQ">Дальше</button></div>`;$('nextQ').onclick=next};$('checkTyped').onclick=check;input.onkeydown=e=>{if(e.key==='Enter')check()}}
function answerOK(a,b){let aa=norm(a),bb=norm(b);if(aa===bb)return true;let parts=String(b).split(/[\/,;]/).map(norm).filter(Boolean);return parts.includes(aa)}
function choiceQ(w){$('qtype').textContent='Выбери перевод';$('questionBody').innerHTML=`<div class="qword">${esc(w.word)}</div>`;let opts=shuffle([w.translation,...shuffle(state.words.filter(x=>x.id!==w.id)).slice(0,3).map(x=>x.translation)]);$('answer').innerHTML=`<div class="choices">${opts.map(o=>`<button class="choice" data-val="${esc(o)}">${esc(o)}</button>`).join('')}</div>`;$('answer').querySelectorAll('.choice').forEach(b=>b.onclick=()=>{let ok=norm(b.dataset.val)===norm(w.translation);record(ok);$('answer').querySelectorAll('.choice').forEach(x=>{x.disabled=true;if(norm(x.dataset.val)===norm(w.translation))x.classList.add('correct');else if(x===b&&!ok)x.classList.add('wrong')});$('answer').insertAdjacentHTML('beforeend','<div class="actions" style="justify-content:center"><button class="btn" id="nextQ">Дальше</button></div>');$('nextQ').onclick=next})}
function flashQ(w){$('qtype').textContent='Карточка';$('questionBody').innerHTML=`<div class="flash-card" id="flashCard"><button class="btn alt" id="flashSpeak" type="button" style="margin-bottom:18px">🔊 Произнести</button><div class="flash-main">${esc(w.word)}</div><div class="flash-tip">Нажми на карточку, чтобы увидеть перевод</div></div>`;$('flashSpeak').onclick=e=>{e.stopPropagation();speak(w.word)};let open=false;$('flashCard').onclick=()=>{if(open)return;open=true;$('flashCard').innerHTML=`<button class="btn alt" id="flashSpeakOpen" type="button" style="margin-bottom:18px">🔊 Произнести</button><div class="flash-main">${esc(w.word)}</div><div class="flash-tr">${esc(w.translation)}</div>${w.example?`<div class="flash-tip">${esc(w.example)}</div>`:''}`;$('flashSpeakOpen').onclick=e=>{e.stopPropagation();speak(w.word)};$('answer').innerHTML='<div class="actions" style="justify-content:center"><button class="btn bad" id="noKnow">Не помню</button><button class="btn good" id="know">Знаю</button></div>';$('noKnow').onclick=()=>{record(false);next()};$('know').onclick=()=>{record(true);next()}}}
function listenQ(w){$('qtype').textContent='Аудирование';$('questionBody').innerHTML='<button class="listen-btn" id="listenPlay" aria-label="Произнести">🔊</button><div class="flash-tip">Нажми и напиши слово, которое услышал</div>';$('answer').innerHTML='<input id="typedInput" placeholder="Что ты услышал?" autocomplete="off" autocapitalize="none"><div class="actions" style="justify-content:center"><button class="btn" id="checkTyped">Проверить</button></div>';let play=()=>speak(w.word);$('listenPlay').onclick=play;setTimeout(play,250);let input=$('typedInput');let check=()=>{let val=input.value.trim();if(!val)return;let ok=answerOK(val,w.word);record(ok);$('answer').innerHTML=`<div class="resultBox ${ok?'good':'bad'}"><b>${ok?'Верно ✓':'Неверно ✕'}</b>${ok?'':`<div style="margin-top:6px;color:var(--text)">Это было: <b>${esc(w.word)}</b></div>`}</div><div class="actions" style="justify-content:center"><button class="btn alt" id="hearAgain">🔊 Ещё раз</button><button class="btn" id="nextQ">Дальше</button></div>`;$('hearAgain').onclick=play;$('nextQ').onclick=next};$('checkTyped').onclick=check;input.onkeydown=e=>{if(e.key==='Enter')check()}}
function speak(text){if(!('speechSynthesis'in window))return alert('На этом устройстве озвучка недоступна');speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.82;let v=speechSynthesis.getVoices().find(v=>/^en/i.test(v.lang));if(v)u.voice=v;speechSynthesis.speak(u)}
function record(ok){let w=cw();sess.total++;w.seen=(w.seen||0)+1;if(ok){sess.correct++;w.correct=(w.correct||0)+1;w.level=Math.min(6,(w.level||0)+1);let days=[0,1,2,4,7,14,30][w.level]||30;w.nextReview=Date.now()+days*86400000}else{w.wrong=(w.wrong||0)+1;w.level=Math.max(0,(w.level||0)-2);w.nextReview=Date.now()+10*60000}localStorage.setItem(KEY,JSON.stringify(state));$('live').textContent=`верно ${sess.correct}`}
function next(){sess.i++;showQ()}
function finish(){state.stats.sessions++;state.stats.correct+=sess.correct;state.stats.total+=sess.total;let t=todayKey(),d=state.stats.daily[t]||{sessions:0,correct:0,total:0};d.sessions++;d.correct+=sess.correct;d.total+=sess.total;state.stats.daily[t]=d;if(state.stats.lastDate!==t){let y=new Date(Date.now()-86400000).toISOString().slice(0,10);state.stats.streak=state.stats.lastDate===y?(state.stats.streak||0)+1:1;state.stats.lastDate=t}save();let pct=sess.total?Math.round(sess.correct/sess.total*100):0;$('session').classList.add('hide');$('result').classList.remove('hide');$('score').textContent=pct+'%';$('scoreText').textContent=`${sess.correct} из ${sess.total} правильных. Ошибочные слова будут появляться чаще.`}
$('again').onclick=()=>{$('result').classList.add('hide');$('setup').classList.remove('hide');start($('count').value)};$('homeBtn').onclick=()=>{$('result').classList.add('hide');$('setup').classList.remove('hide');go('home')};
$('exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='slovotrener-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('importFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let x=JSON.parse(await f.text());if(!Array.isArray(x.words))throw 0;state=x;state.stats ||= empty().stats;state.stats.daily ||= {};save();alert('Импорт готов')}catch{alert('Не удалось прочитать файл')}e.target.value=''};
$('resetBtn').onclick=()=>{if(confirm('Удалить личный прогресс и свои слова? Общий словарь останется.')){localStorage.removeItem(KEY);state=load();save()}};
if('serviceWorker'in navigator){addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').then(r=>r.update()).catch(()=>{}))}
render();